### ISSUE TITLE
EPIC: User management

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.beacon.admin#11]
**UPDATE** This EPIC has been split into several user stories. Follow progress there...

As a Beacon Network admin I want to:
- [x] force the new user to change the default password at the first login or after a password reset;
- [x] have the possibility to have more than one admin user;
- [x] be able to assign admin rights to each user with a flag;
- [x] manage roles and groups (eg. each group member is able to see and configure only the beacon assigned to his group, the admin of a group manages also the users role of the people assigned to his group, etc.).
- [x] be able to assign to each user one role for each group he is assignet to. The role of a user can be different from group to group.
- [x] have more roles according to the roles agreen during the kick off;
- [x] In addition, a user can reset his password, ask for a forgotten login information and can, if new, also generate a new login automatically. An “admin” will then receive a notification and can accept or decline the new user. All of these functionality should be handled over email
